//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CLCiTrentConversionService.com.webitrent.ce0286de {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ETADM086SSBinding", Namespace="urn:uniface:applic:wrapped:services:ETADM086SS")]
    public partial class ETADM086SSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ACCEPTOperationCompleted;
        
        private System.Threading.SendOrPostCallback CHK_CONV_NEWOperationCompleted;
        
        private System.Threading.SendOrPostCallback CHK_CONV_STATUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback EXECOperationCompleted;
        
        private System.Threading.SendOrPostCallback QUITOperationCompleted;
        
        private System.Threading.SendOrPostCallback RUN_CONVOperationCompleted;
        
        private System.Threading.SendOrPostCallback RUN_CONV_NEWOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ETADM086SSService() {
            this.Url = global::CLCiTrentConversionService.Properties.Settings.Default.CLCiTrentConversionService_com_webitrent_ce0286de_ETADM086SSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ACCEPTCompletedEventHandler ACCEPTCompleted;
        
        /// <remarks/>
        public event CHK_CONV_NEWCompletedEventHandler CHK_CONV_NEWCompleted;
        
        /// <remarks/>
        public event CHK_CONV_STATUSCompletedEventHandler CHK_CONV_STATUSCompleted;
        
        /// <remarks/>
        public event EXECCompletedEventHandler EXECCompleted;
        
        /// <remarks/>
        public event QUITCompletedEventHandler QUITCompleted;
        
        /// <remarks/>
        public event RUN_CONVCompletedEventHandler RUN_CONVCompleted;
        
        /// <remarks/>
        public event RUN_CONV_NEWCompletedEventHandler RUN_CONV_NEWCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int ACCEPT() {
            object[] results = this.Invoke("ACCEPT", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ACCEPTAsync() {
            this.ACCEPTAsync(null);
        }
        
        /// <remarks/>
        public void ACCEPTAsync(object userState) {
            if ((this.ACCEPTOperationCompleted == null)) {
                this.ACCEPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnACCEPTOperationCompleted);
            }
            this.InvokeAsync("ACCEPT", new object[0], this.ACCEPTOperationCompleted, userState);
        }
        
        private void OnACCEPTOperationCompleted(object arg) {
            if ((this.ACCEPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ACCEPTCompleted(this, new ACCEPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int CHK_CONV_NEW([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_QUEUE_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_STATUS, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_LOG_FILE_DATA, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_EXC_FILE_DATA, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_SUC_FILE_DATA, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_ERROR_MSG) {
            object[] results = this.Invoke("CHK_CONV_NEW", new object[] {
                        P_QUEUE_ID});
            P_STATUS = ((string)(results[1]));
            P_LOG_FILE_DATA = ((string)(results[2]));
            P_EXC_FILE_DATA = ((string)(results[3]));
            P_SUC_FILE_DATA = ((string)(results[4]));
            P_ERROR_MSG = ((string)(results[5]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CHK_CONV_NEWAsync(string P_QUEUE_ID) {
            this.CHK_CONV_NEWAsync(P_QUEUE_ID, null);
        }
        
        /// <remarks/>
        public void CHK_CONV_NEWAsync(string P_QUEUE_ID, object userState) {
            if ((this.CHK_CONV_NEWOperationCompleted == null)) {
                this.CHK_CONV_NEWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCHK_CONV_NEWOperationCompleted);
            }
            this.InvokeAsync("CHK_CONV_NEW", new object[] {
                        P_QUEUE_ID}, this.CHK_CONV_NEWOperationCompleted, userState);
        }
        
        private void OnCHK_CONV_NEWOperationCompleted(object arg) {
            if ((this.CHK_CONV_NEWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CHK_CONV_NEWCompleted(this, new CHK_CONV_NEWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int CHK_CONV_STATUS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_QUEUE_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_STATUS, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_ERROR_MSG) {
            object[] results = this.Invoke("CHK_CONV_STATUS", new object[] {
                        P_QUEUE_ID});
            P_STATUS = ((string)(results[1]));
            P_ERROR_MSG = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CHK_CONV_STATUSAsync(string P_QUEUE_ID) {
            this.CHK_CONV_STATUSAsync(P_QUEUE_ID, null);
        }
        
        /// <remarks/>
        public void CHK_CONV_STATUSAsync(string P_QUEUE_ID, object userState) {
            if ((this.CHK_CONV_STATUSOperationCompleted == null)) {
                this.CHK_CONV_STATUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCHK_CONV_STATUSOperationCompleted);
            }
            this.InvokeAsync("CHK_CONV_STATUS", new object[] {
                        P_QUEUE_ID}, this.CHK_CONV_STATUSOperationCompleted, userState);
        }
        
        private void OnCHK_CONV_STATUSOperationCompleted(object arg) {
            if ((this.CHK_CONV_STATUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CHK_CONV_STATUSCompleted(this, new CHK_CONV_STATUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int EXEC() {
            object[] results = this.Invoke("EXEC", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EXECAsync() {
            this.EXECAsync(null);
        }
        
        /// <remarks/>
        public void EXECAsync(object userState) {
            if ((this.EXECOperationCompleted == null)) {
                this.EXECOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEXECOperationCompleted);
            }
            this.InvokeAsync("EXEC", new object[0], this.EXECOperationCompleted, userState);
        }
        
        private void OnEXECOperationCompleted(object arg) {
            if ((this.EXECCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EXECCompleted(this, new EXECCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int QUIT() {
            object[] results = this.Invoke("QUIT", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void QUITAsync() {
            this.QUITAsync(null);
        }
        
        /// <remarks/>
        public void QUITAsync(object userState) {
            if ((this.QUITOperationCompleted == null)) {
                this.QUITOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQUITOperationCompleted);
            }
            this.InvokeAsync("QUIT", new object[0], this.QUITOperationCompleted, userState);
        }
        
        private void OnQUITOperationCompleted(object arg) {
            if ((this.QUITCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QUITCompleted(this, new QUITCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int RUN_CONV([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CONV_TYPE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CONV_DIR, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CONV_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_PEOPLE_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_FS, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_ORG_NAME, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_USER_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_USER_PWD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_LOG_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_EXC_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_SUC_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_QUEUE_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_ERROR_MSG) {
            object[] results = this.Invoke("RUN_CONV", new object[] {
                        P_CONV_TYPE,
                        P_CONV_DIR,
                        P_CONV_FILE,
                        P_PEOPLE_ID,
                        P_FS,
                        P_ORG_NAME,
                        P_USER_NM,
                        P_USER_PWD});
            P_LOG_FILE = ((string)(results[1]));
            P_EXC_FILE = ((string)(results[2]));
            P_SUC_FILE = ((string)(results[3]));
            P_QUEUE_ID = ((string)(results[4]));
            P_ERROR_MSG = ((string)(results[5]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RUN_CONVAsync(string P_CONV_TYPE, string P_CONV_DIR, string P_CONV_FILE, string P_PEOPLE_ID, string P_FS, string P_ORG_NAME, string P_USER_NM, string P_USER_PWD) {
            this.RUN_CONVAsync(P_CONV_TYPE, P_CONV_DIR, P_CONV_FILE, P_PEOPLE_ID, P_FS, P_ORG_NAME, P_USER_NM, P_USER_PWD, null);
        }
        
        /// <remarks/>
        public void RUN_CONVAsync(string P_CONV_TYPE, string P_CONV_DIR, string P_CONV_FILE, string P_PEOPLE_ID, string P_FS, string P_ORG_NAME, string P_USER_NM, string P_USER_PWD, object userState) {
            if ((this.RUN_CONVOperationCompleted == null)) {
                this.RUN_CONVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRUN_CONVOperationCompleted);
            }
            this.InvokeAsync("RUN_CONV", new object[] {
                        P_CONV_TYPE,
                        P_CONV_DIR,
                        P_CONV_FILE,
                        P_PEOPLE_ID,
                        P_FS,
                        P_ORG_NAME,
                        P_USER_NM,
                        P_USER_PWD}, this.RUN_CONVOperationCompleted, userState);
        }
        
        private void OnRUN_CONVOperationCompleted(object arg) {
            if ((this.RUN_CONVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RUN_CONVCompleted(this, new RUN_CONVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", ResponseNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int RUN_CONV_NEW([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CONV_TYPE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CONV_DIR, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CONV_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_PEOPLE_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_FS, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_ORG_NAME, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_USER_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_USER_PWD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_LOG_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_EXC_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_SUC_FILE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_QUEUE_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string P_ERROR_MSG) {
            object[] results = this.Invoke("RUN_CONV_NEW", new object[] {
                        P_CONV_TYPE,
                        P_CONV_DIR,
                        P_CONV_FILE,
                        P_PEOPLE_ID,
                        P_FS,
                        P_ORG_NAME,
                        P_USER_NM,
                        P_USER_PWD});
            P_LOG_FILE = ((string)(results[1]));
            P_EXC_FILE = ((string)(results[2]));
            P_SUC_FILE = ((string)(results[3]));
            P_QUEUE_ID = ((string)(results[4]));
            P_ERROR_MSG = ((string)(results[5]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RUN_CONV_NEWAsync(string P_CONV_TYPE, string P_CONV_DIR, string P_CONV_FILE, string P_PEOPLE_ID, string P_FS, string P_ORG_NAME, string P_USER_NM, string P_USER_PWD) {
            this.RUN_CONV_NEWAsync(P_CONV_TYPE, P_CONV_DIR, P_CONV_FILE, P_PEOPLE_ID, P_FS, P_ORG_NAME, P_USER_NM, P_USER_PWD, null);
        }
        
        /// <remarks/>
        public void RUN_CONV_NEWAsync(string P_CONV_TYPE, string P_CONV_DIR, string P_CONV_FILE, string P_PEOPLE_ID, string P_FS, string P_ORG_NAME, string P_USER_NM, string P_USER_PWD, object userState) {
            if ((this.RUN_CONV_NEWOperationCompleted == null)) {
                this.RUN_CONV_NEWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRUN_CONV_NEWOperationCompleted);
            }
            this.InvokeAsync("RUN_CONV_NEW", new object[] {
                        P_CONV_TYPE,
                        P_CONV_DIR,
                        P_CONV_FILE,
                        P_PEOPLE_ID,
                        P_FS,
                        P_ORG_NAME,
                        P_USER_NM,
                        P_USER_PWD}, this.RUN_CONV_NEWOperationCompleted, userState);
        }
        
        private void OnRUN_CONV_NEWOperationCompleted(object arg) {
            if ((this.RUN_CONV_NEWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RUN_CONV_NEWCompleted(this, new RUN_CONV_NEWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ACCEPTCompletedEventHandler(object sender, ACCEPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ACCEPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ACCEPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CHK_CONV_NEWCompletedEventHandler(object sender, CHK_CONV_NEWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CHK_CONV_NEWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CHK_CONV_NEWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string P_STATUS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string P_LOG_FILE_DATA {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string P_EXC_FILE_DATA {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string P_SUC_FILE_DATA {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string P_ERROR_MSG {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CHK_CONV_STATUSCompletedEventHandler(object sender, CHK_CONV_STATUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CHK_CONV_STATUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CHK_CONV_STATUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string P_STATUS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string P_ERROR_MSG {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EXECCompletedEventHandler(object sender, EXECCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EXECCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EXECCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QUITCompletedEventHandler(object sender, QUITCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QUITCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QUITCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RUN_CONVCompletedEventHandler(object sender, RUN_CONVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RUN_CONVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RUN_CONVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string P_LOG_FILE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string P_EXC_FILE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string P_SUC_FILE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string P_QUEUE_ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string P_ERROR_MSG {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RUN_CONV_NEWCompletedEventHandler(object sender, RUN_CONV_NEWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RUN_CONV_NEWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RUN_CONV_NEWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string P_LOG_FILE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string P_EXC_FILE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string P_SUC_FILE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string P_QUEUE_ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string P_ERROR_MSG {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591